name: quantum_muscle
description: New Age Of Muscles

publish_to: "none"

version: 3.5.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.3.1
  # cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_hooks: ^0.18.5+1
  flutter_native_splash: ^2.2.17
  flutter_screenutil: ^5.6.0
  get: ^4.6.5
  get_storage: ^2.0.3
  google_nav_bar: ^5.0.6
  image_picker: ^0.8.6+1
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#E0E0E0"
  image: assets/lightTheme.png
  color_dark: "#212121"
  image_dark: assets/darkTheme.png
  android: true
  ios: true
  web: true
flutter:
  uses-material-design: true
  assets:
    - assets/lightTheme.png
    - assets/darkTheme.png

  fonts:
    - family: family
      fonts:
        - asset: assets/font.ttf
